name: Secrets Demo

on:
  workflow_dispatch:   # run manually

jobs:
  show-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Use secret in env
        env:
          TOKEN: ${{ secrets.MY_SECRET_TOKEN }}
        run: |
          echo "I can access the secret in this step"
          echo "But if I try to print TOKEN directly, GitHub masks it:"
          echo "TOKEN=$TOKEN"
